worker_processes auto;
worker_priority -5;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 45;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;
    gzip_min_length 256;
    client_max_body_size 2048M;

    server {
        listen 80;

        # 1. Отдача фронтенда (React статика)
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        # 2. Проксирование запросов к бэкенду FastAPI
        # Все запросы, начинающиеся с /api, Nginx отправит на FastAPI
        location /api/ {
            proxy_pass http://fastapi:8000/api/; # 'backend' — это имя сервиса в docker-compose
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Повторяем лимит для загрузки больших файлов на бэк
            client_max_body_size 100M;

            # Настройки таймаутов для загрузки больших файлов
            proxy_read_timeout 300s;
            proxy_connect_timeout 300s;
        }
    }
}