FROM python:3.12-slim

# Устанавливаем uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Рабочая директория
WORKDIR /app

# Копируем зависимости отдельно
COPY pyproject.toml uv.lock ./

# Venv вне /app
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Установка зависимостей
RUN uv sync --frozen --no-cache

# Копируем проект
COPY . .

# FastAPI порт
EXPOSE 8000

# Запуск FastAPI
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]