[mypy]
python_version = 3.12
warn_return_any = True
disallow_untyped_defs = True      # ЗАПРЕЩАЕТ функции без аннотаций типов (обязательно!)
disallow_incomplete_defs = True   # Запрещает частичные реализации
check_untyped_defs = True         # Проверяет логику внутри функций без типов
no_implicit_optional = True        # Делает явным, что аргумент может быть None
strict = False                    # Можно начать не со строгого режима, а постепенно ужесточать

[mypy-backend.auth.*]
# Здесь можно делать исключения для старых файлов, если пока не хочешь их править
ignore_missing_imports = False

[mypy-aiobotocore.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True