"""ondelete=CASCADE

Revision ID: 5386a82c416c
Revises: ff264a6d248d
Create Date: 2026-06-09 06:47:29.561530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5386a82c416c"
down_revision: Union[str, Sequence[str], None] = "ff264a6d248d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("folders_parent_id_fkey"), "folders", type_="foreignkey")
    op.create_foreign_key(
        None, "folders", "folders", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "folders", type_="foreignkey")
    op.create_foreign_key(
        op.f("folders_parent_id_fkey"), "folders", "folders", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###
