"""folder, files

Revision ID: ff264a6d248d
Revises: a6cd92f48179
Create Date: 2026-06-07 17:08:46.425040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff264a6d248d'
down_revision: Union[str, Sequence[str], None] = 'a6cd92f48179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', 'user_id', name='uq_folder_unique_name')
    )
    op.create_index('ix_folders_user_parent', 'folders', ['user_id', 'parent_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'folder_id', 'user_id', name='uq_file_unique_name')
    )
    op.create_index('ix_files_s3_key', 'files', ['s3_key'], unique=False)
    op.create_index('ix_files_user_folder', 'files', ['user_id', 'folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_user_folder', table_name='files')
    op.drop_index('ix_files_s3_key', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_folders_user_parent', table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
